[package]
name = "rpatch"
version = "0.1.0"
edition = "2021"
authors = ["zerodegress"]
repository = "https://github.com/zerodegress/rpatch"
license = "MIT"

[dependencies]
nom = "7.1.3"
patch = "0.7.0"
