[package]
name = "rpatch"
version = "0.1.0"
edition = "2021"
authors = ["zerodegress"]
repository = "https://github.com/zerodegress/rpatch"
license = "MIT"
description = "A simple tool aimed to patch files using Unified Diff Format patch."

[dependencies]
patch = "0.7.0"
